dist: trusty
sudo: required
language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "synthesizer" # the key of the org you chose at step #3
    token:
      secure: a455c0aec55b9f2f273bc638b9e8026e6e5a7d78 # encrypted value of your token
script:
    - python tst_vibrato_view.py
    - sonar-scanner
